services:
  - type: web
    name: networkk-website
    runtime: node
    plan: free
    rootDir: apps/website
    buildCommand: cd ../.. && npm install && cd packages/content-bridge && npm run build && cd ../../apps/website && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: anupama.singh@networkk.in
      - key: TO_EMAIL
        value: anupama.singh@networkk.in
